//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ws_PruebaEstudio.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.PruebaEstudioSoap")]
    public interface PruebaEstudioSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        ws_PruebaEstudio.ServiceReference1.HelloWorldResponse HelloWorld(ws_PruebaEstudio.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ws_PruebaEstudio.ServiceReference1.HelloWorldResponse> HelloWorldAsync(ws_PruebaEstudio.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RetornarAlumno", ReplyAction="*")]
        bool RetornarAlumno();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RetornarAlumno", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> RetornarAlumnoAsync();
        
        // CODEGEN: Generating message contract since element name a from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerificarCuenta", ReplyAction="*")]
        ws_PruebaEstudio.ServiceReference1.VerificarCuentaResponse VerificarCuenta(ws_PruebaEstudio.ServiceReference1.VerificarCuentaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerificarCuenta", ReplyAction="*")]
        System.Threading.Tasks.Task<ws_PruebaEstudio.ServiceReference1.VerificarCuentaResponse> VerificarCuentaAsync(ws_PruebaEstudio.ServiceReference1.VerificarCuentaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ws_PruebaEstudio.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ws_PruebaEstudio.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ws_PruebaEstudio.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ws_PruebaEstudio.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerificarCuentaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerificarCuenta", Namespace="http://tempuri.org/", Order=0)]
        public ws_PruebaEstudio.ServiceReference1.VerificarCuentaRequestBody Body;
        
        public VerificarCuentaRequest() {
        }
        
        public VerificarCuentaRequest(ws_PruebaEstudio.ServiceReference1.VerificarCuentaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerificarCuentaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string a;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string b;
        
        public VerificarCuentaRequestBody() {
        }
        
        public VerificarCuentaRequestBody(string a, string b) {
            this.a = a;
            this.b = b;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerificarCuentaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerificarCuentaResponse", Namespace="http://tempuri.org/", Order=0)]
        public ws_PruebaEstudio.ServiceReference1.VerificarCuentaResponseBody Body;
        
        public VerificarCuentaResponse() {
        }
        
        public VerificarCuentaResponse(ws_PruebaEstudio.ServiceReference1.VerificarCuentaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerificarCuentaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool VerificarCuentaResult;
        
        public VerificarCuentaResponseBody() {
        }
        
        public VerificarCuentaResponseBody(bool VerificarCuentaResult) {
            this.VerificarCuentaResult = VerificarCuentaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PruebaEstudioSoapChannel : ws_PruebaEstudio.ServiceReference1.PruebaEstudioSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PruebaEstudioSoapClient : System.ServiceModel.ClientBase<ws_PruebaEstudio.ServiceReference1.PruebaEstudioSoap>, ws_PruebaEstudio.ServiceReference1.PruebaEstudioSoap {
        
        public PruebaEstudioSoapClient() {
        }
        
        public PruebaEstudioSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PruebaEstudioSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PruebaEstudioSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PruebaEstudioSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ws_PruebaEstudio.ServiceReference1.HelloWorldResponse ws_PruebaEstudio.ServiceReference1.PruebaEstudioSoap.HelloWorld(ws_PruebaEstudio.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ws_PruebaEstudio.ServiceReference1.HelloWorldRequest inValue = new ws_PruebaEstudio.ServiceReference1.HelloWorldRequest();
            inValue.Body = new ws_PruebaEstudio.ServiceReference1.HelloWorldRequestBody();
            ws_PruebaEstudio.ServiceReference1.HelloWorldResponse retVal = ((ws_PruebaEstudio.ServiceReference1.PruebaEstudioSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ws_PruebaEstudio.ServiceReference1.HelloWorldResponse> ws_PruebaEstudio.ServiceReference1.PruebaEstudioSoap.HelloWorldAsync(ws_PruebaEstudio.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ws_PruebaEstudio.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            ws_PruebaEstudio.ServiceReference1.HelloWorldRequest inValue = new ws_PruebaEstudio.ServiceReference1.HelloWorldRequest();
            inValue.Body = new ws_PruebaEstudio.ServiceReference1.HelloWorldRequestBody();
            return ((ws_PruebaEstudio.ServiceReference1.PruebaEstudioSoap)(this)).HelloWorldAsync(inValue);
        }
        
        public bool RetornarAlumno() {
            return base.Channel.RetornarAlumno();
        }
        
        public System.Threading.Tasks.Task<bool> RetornarAlumnoAsync() {
            return base.Channel.RetornarAlumnoAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ws_PruebaEstudio.ServiceReference1.VerificarCuentaResponse ws_PruebaEstudio.ServiceReference1.PruebaEstudioSoap.VerificarCuenta(ws_PruebaEstudio.ServiceReference1.VerificarCuentaRequest request) {
            return base.Channel.VerificarCuenta(request);
        }
        
        public bool VerificarCuenta(string a, string b) {
            ws_PruebaEstudio.ServiceReference1.VerificarCuentaRequest inValue = new ws_PruebaEstudio.ServiceReference1.VerificarCuentaRequest();
            inValue.Body = new ws_PruebaEstudio.ServiceReference1.VerificarCuentaRequestBody();
            inValue.Body.a = a;
            inValue.Body.b = b;
            ws_PruebaEstudio.ServiceReference1.VerificarCuentaResponse retVal = ((ws_PruebaEstudio.ServiceReference1.PruebaEstudioSoap)(this)).VerificarCuenta(inValue);
            return retVal.Body.VerificarCuentaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ws_PruebaEstudio.ServiceReference1.VerificarCuentaResponse> ws_PruebaEstudio.ServiceReference1.PruebaEstudioSoap.VerificarCuentaAsync(ws_PruebaEstudio.ServiceReference1.VerificarCuentaRequest request) {
            return base.Channel.VerificarCuentaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ws_PruebaEstudio.ServiceReference1.VerificarCuentaResponse> VerificarCuentaAsync(string a, string b) {
            ws_PruebaEstudio.ServiceReference1.VerificarCuentaRequest inValue = new ws_PruebaEstudio.ServiceReference1.VerificarCuentaRequest();
            inValue.Body = new ws_PruebaEstudio.ServiceReference1.VerificarCuentaRequestBody();
            inValue.Body.a = a;
            inValue.Body.b = b;
            return ((ws_PruebaEstudio.ServiceReference1.PruebaEstudioSoap)(this)).VerificarCuentaAsync(inValue);
        }
    }
}
